import type { NextPage } from 'next'
import Head from "next/head";
import Navbar from "../components/Navbar";
import SliderImg from "../components/SliderImg";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home | Unimodas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <SliderImg />
      <main className="container"></main>
    </div>
  );
};

export default Home
