import Head from "next/head";
import React, { useState } from "react";
import FiltroProdutos from "../components/Filtro";
import Filtro from "../components/Filtro";
import Footer from "../components/Footer";
import Lancamentos from "../components/Lancamentos";
import Navbar from "../components/Navbar";

export default function produtos() {
  const [isOpen, setIsOpen] = useState(false);

  const handleToggle = () => {
    setIsOpen(!isOpen);
  };
  return (
    <div>
      <Head>
        <title>Produtos | Unimodas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar handleToggle={handleToggle} />

      <FiltroProdutos />
      {/* <Lancamentos /> */}
      <Footer />
      <main className="container"></main>
    </div>
  );
}
