import Head from "next/head";
import React from "react";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import SobreNos from "../components/Sobre";

export default function Sobre() {
  return (
    <>
      <Head>
        <title>Sobre nós | Unimodas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <SobreNos />
      <Footer />
    </>
  );
}
